name: chatbot
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2
  chat_bubbles: ^1.7.0
  lottie: ^1.4.3
  share_plus: ^7.2.1
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_markdown: ^0.6.14
  uuid: ^4.0.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
